### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by petedoyle0606** [gbgplc/identity-solution#1]
Please re-proof this text - change it's to its as necessary.
[Authentication-Overview](../wiki/Authentication-Overview)

**Comment by PhlashGBG** [comment]
Thanks Pete, your direct message indicates the following fixes:
 * its -> it's (possessive form) in several places.
 * Pre-requisite -> Prerequisite.

**Comment by PhlashGBG** [comment]
https://github.com/gbgplc/identity-solution/wiki/Authentication-Overview/c22665233caada26c4fe0c781e9a681b22fc2ea9
